apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-auth-for-teslamate
  namespace: postgresql
spec:
  encryptedData:
    values.yaml: AgA/+2Xnfb1Up9DCcYz9oAj6L1ye4EQdeX651wCUheeDfxw2NtFiZo1igAFhr9OawwVWQJwZ0bd2geUekaX1K+DDQS+PgcVkvMTNiJ6c+L6KFRz8JaDz3p+vtSPK3lW5zU2e1mT5cYogIp58QlZ+QAod648wZRb9TTKQvHV2Gzy5ofggXeqe/jnt0gQYJK9UIhixopYKbPHxaxdmwnB2YlLdnunsz6rST5zD5qe5nLYHqxPFSZdiNcQDpWdvDmLJvOFYEtJ/bwSRpMC9NeXF3u7+PFAWIOjWoKdLvK3eAAhuGQmx+EXXJGFnu8ku0fAW9uqBZRG459jarvAx3fxkvB7288QoZQlew1rqA4eoS8YjS9XuB131mOBm56mAuEVvANGgmJtgqgruZyDwRET0UDQph7zNDnLNdcr4ocDRi844+3FUP1PnO8myoitUxxcmjcDQxdE2KaEHRzK7jREUttVJp53Tj5fTrZHbzFebG4CdJMjWiIw6B4aDXaycfzjbFI0iIjzbgY8eep0icFWp4ne7Kg2p+9EmJykJK6Q2Ev3lsbW7TiHnHUdplZSpFNsFHWG0C63Qntjo+9ZZU142qUQrYLjn/d7aAF0k8KEzW3OsR+57I9CJI5Wdq5Ng+tWk0sijabGAoKVdtCLnOg3rUjH2HHofNlD+mGnGXypMeR1/EI0lJxCGtb0xzSpcGwRgd1NFkm+UoKehRTu6mwdMM4RMBVOEk7/dKL0AdEaF/xoilDEcnsoz0vm4lwkqKLrkN2nNV6ZNYQgzjTuK0UApz9NM+MjxXmFzuyXz
  template:
    metadata:
      creationTimestamp: null
      name: db-auth-for-teslamate
      namespace: postgresql

