---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lovenotes-admin-auth
  namespace: lovenotes
spec:
  encryptedData:
    users: AgAbqh6iyb0ySSlRkKXP246wERaSEAYZH0pS7sCg9NulB9T7AsHXT5ywWUlSg2mNEpU9CX6hXkVh6WX+yuR6+9V73cYa0tldEn6+6ODrcosBAYCGStMSw8IWOYQHDmMyB/sbClXcjHu6f/86pIkM1AocqMZDKS/qu/u+c1SO/JIwJZn9C1YBqv02zewcxBIuBXvNXyWsvbRiLERnADuaUK41dIQLsFRS8oeaUfPTGKw8t5orXlYk7wDvneXeMxmiIgli13OHYOGYbrp63J6Qn2k0zoZ6SZOT4FeLDxKa/7dwD7/M/SCnwkj4oVa7fd8DuHXu5UbaDye/rvicl2t4+FxkNA1AF/w+/A+CY+W0tEOHWySoz7H+THNOeyqTSDeWj5m1EI5XEyhIBsBP/ZYS6yMeLZhgLEXcnhFlgRlzeQVZIURErWJTymyrd1TBZlF6kHA5O3Jw03oBJ4+oc4QrOefmT2ju+JoHF5f8fkUFvq/kQEoXh2HV3D/a0pfSkMfp3+z5Jp5PP3Vqr2kI6X7TQrCex1i42L/UIy0IV9L1XY+LLvM1qdvBYKo4Lz0qNST+I+RpJ5LyV57ewHxxyE2XwTU8qyhtb7VY2UQ0Tkb/Ob0ExxvIWEkqAcEdCLM0rXZKXf9+Ibah9QmMQeFtaprO2wHvMbDwH7Fv0Np2ukj4d46htMyF6YgnYHjVSUEbmxkpk8vGrX8vDDG7W+sqKbiSiPLexF2n1kBHiwr0FJTtMa4pUgJ6VxIGv1AgfH+OLmUhf1DMpp90P+AO88QXh1MTjL+sjHEZGQ==
  template:
    metadata:
      name: lovenotes-admin-auth
      namespace: lovenotes
