---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDJqDnmKDCZanzdRaV/J+eevBCUSxhtvJNZEJa8N4binFbjamWKd2dY4Ff875FCCF7VfqXWE7T0yPfknQBOMyL9nKZT37Xa6dpr831ic1SLkaug9ryqVtyxmnvMvLlfNBCZggsOnYJsxUDoHI1l8vdmd8UFHCXJDZWTsD5Yl4lczSLvMJ5Dj4S9gvfUY3g9WsMlD6aUG6l9i4WHp3c//5uWatkCoqOIgSZnnc2pymv5dLf4yj9hPO9xiZ46Zr+InZvM2xxKM6irghNbKZy1hAvEwxAOuEvE7S3bmDmPcMy0z/w8ipOlnhCRMfLh2FUOUqUouQ+NMxmfGSA43U6CVGwOHG87r7uv/B7o49ll51hLOevD6EsXAY+8sZOyCVQPi3hgm4xKmjV6iwpa7lOqIiZQ1NFEkaMtdq6lQPGZ5aldrrOQKJg9fWUMwDDm4yp8bsjba8WLGRg6Ur4L4DvugugDM9vYqvaA/lfJjBm1Ky88GcHexl8kZlw6m6YUEHZ6ubiDzihTdifmqpMfxha+akq37aiUgJSAtWjiKibKPbzTYqFAiYg0o8ZogjCZQZyEITyTsAG7LH+i2a2DDvy48h3rpfqFPHRS6OCYnYu4Jbdn84NsDpgFgFF2woYZR3bLTm07w88fwHMvs7BxW5I+jVDH4AxvMBFAfq3uyjpeqWOV0aUItG5rCUcf8qbv+S4xHShCFOkrFv56HzrtNrHFZDf+CPc2Ytj7qhzJs2WEwgsoKpK3Xb9iD+oO
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
