---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAVgFdYii4USVVUxwQnWVUgZFQi7YAz/xjzd8lIReIiH/vEV54y+Dr+jA4An/Walxqxm39sKvBveyQW15MrsFssTmUvVvPPMnWqT4gZOuPnifo2UhvUnuyW5N2hHQV8+VOVUJwbx5OBMkvoxIl1zUiYucXvdJHsHbSCbc1ttcuYjmDhsXxgee3dfTs9S/MocrkvHMgZ/7lYbiPdwuny7CRyaDFJAbSu9lsnFj1tqn1NpHM84NsiouRu2aG1nqcywT5OAa8VEeK4T2qbBUEgIfyZEdVPk81cR8sqxcFYefVsXiHwBw9R23yrzZMTnAVUuO1xPLNciXdsCiSykc8S+uS5l2up0Owx5MMNpzX2TO+czKMFy7DgpGnXIn4VAXUeJtUDEdsOaEeiFTKkGr1EDjW/umfwpR3zw9qvlpw3SW2VmeO19iZgP3SPdi9tfua6IZV9ozqVNWJSmmYZzrdJnQrecYYqAqZo9HYsGuMMnbElUmrk+sPdJXNHrx9iw745WOoS0FqqwrArDqgGmb+Kn8JnOSA2s2axpPMT50xcTtfnbCFszvd9brFb9ZwktY8OpsgsDIwK/pJVMdyopdrh4KohhOCphVq9z+Ip+QXH5DfKMaKAgZ19CdFJtJ2e+lrwQ7Ho2kJMKTBVeKKyEutMA4qg8RFBUS0Mxu340TZYqoxirszCb9GEXAtod98nCMgn3cYn11REA1GpY4f4m8ViBNdRYSNqQhMSu9DguGxA7OMWd2U1Lu6iVAv3
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
