---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAgWn+dyMDfqU5tnRPjasI6whLzv0o4RIKADh9rScrCqeFcLSJvYEVKo4fvcU6Zi8bSvSgAm/9KnBXZV9IO3BPbIHBQEWraelPuVLlzC4spzCpiE8CpztBSFRg3qOTGhpXEFmV5rU3Yq9z5AXJiTS6RHr70Wa0NK9o4Gl9HfOKj+/OFMgRjMuqqrnpPOHe15oVi+CUIIU+CJSUtSAT9MX3lysBumWnaJwUk8F8+FqD3Mo4a4TTKwuothbGeIiFOqWJ6NHfW39+P4gteSrqNUYv1VcRWbkMJ1uSpcs7ilYmOsI1E9Bf1kcR4oQeg1fKITi8xpGvY/lRUb10SRk/wBe+wpz11D57mn6L85L9s8p3gTHop/ujzUP83cK0hBdab71l8n/zUi/vqlP6Yi0xHaU+FfgmEX9pX0QFbmt0/uo0MY74xbz6DucQmr7U2Q2FIwvvZfmSRpImct4/R1xrDcGMHRTsWI4mrJ/a5qz2Q0UI7HHuhyj6k1iv0+QQNvb4LvPYf+KplWrHA9xn5+8rz4YF0gZ0bh5vIWwcgBW45A54ENsZeLHmqbQSyxsiqV8svVLeKzr3+8GVdZYN54KRVVsFJad+Nt+l9/1ohIJFSvJ3sIAfzpCeP3SsB/zHHi45ex8YV91pMkvxxclrcFdiwpfbRgWLA6mF79+3atuEQ6l6uawudTn9an+AEXZRbG/egxDHl2AuSa9tJ25NOH2Pq6yUBLZghCWXGs4c8PnsErSfWwihLx0GSfNm/
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
