---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA26JjqfXJXhUeavyvjxijsP+1OXsn3nCHpTSYI6FAou7/Q+AMnFUROKKX7g4wQWfgU7bthPO1xjAVCIu3mvzzEApWDaNMU0jC8IlGZRNtRPTZYap9ywcPAnxrNfztK2nTqaRtdgJ5T36bNMBFCaHYCN+s7+BvBc7XwcSq9+7kYzLWcA9Z9+hn6G2sl459XocNFWRI+wE7e3zyY0Tp8KpeHiM6rGuekhezvjGK1SBcTynYFuzK7TGlGeLpTyCa/ml3AGsb86bxCRVS0gLSQxY6K2BGgdrS9idQHGG+yXvXpENwNOgR++JNtL3yaRvQa7n/hHuI6kgIbPUuSSme7/Z8vWGRIp2PsSBQdsFI3a741D6ucWVy/kAzlgrS1hTOeaLOiwkXF7xObW6kCByTp28QmG2OXfPOPQMuxYf8kFK4ecYx4hvUTT3DgIp4fn+UB/GuEY6C9YWLcmqK/uKDutDd2lxYp0alpqpkxszs4we9Qqd5rJPrBHqWB0s6aWuUJok6DFvhIExtX4Ns935uvBzom761i38m0ICQk7lv+1F8FSI9MC8o4d3xJk94/SExv5HzAMQn3mlncCZgnmX04u4wKoIHX8tq4a6LJiGhzyypxOEGKJEWMAv3I0fkVe/NLU2gFeZds7e7ZerNtCRLvpebwxvIW9sY2KaAUE+7X9CssHYwdB8dG2Fslabtef5UTugM/mtgsIXGUyUvbNOovlEllHaI7WW6rPBsaNNDSHR37fBr5H19FLp6F
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
