---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgA+FnPm9Fa9AjkLPxgZCnXgB+KDaKXkH2N/EQgR/HnWo6iiXIjRoOBPP+q3Gd+/UpILoi/ZagQun6tk4nefLb+9FRPJAVWnTUG8xo8BMvmiJ6TV7gLkzXi1eCXFExMJ9A/BI4JfV5pX2Uip4SFgyyPrPlpt/FyPKeGeLq61M+HflNwWv1Y9Jhe2J9RPSuCm6pAuiRQX2rBKTQ6nPcl1GPZiqiq+TwUSXgay+/hm45sDu7A7tSayBvZEN+CG6YOeWQszpby5X5/6QxyG1ID27vVtsfCopy/RkhU3TBpZPFvP4IxozdfKJI2dVP/uZTvqK1Ru/sJ1jZYI6QTbLSVue+AwUmUATBX+TLXlaf+xAd8fvAfBwOSQ9u1CfkdyMHLAVJUPVcxxICH3Ks0OSEZpdGAZ6cFEnVdP+M9EIIyqGBa8ZVpM0PbUJ7LNDtwIe+ysaNtxXcdWX4AEiOYnemTpDW4ZEQNWVq7h1sWHsV5Bf9MLAMFmWWmGECfzBaUPDrJwWlD6laToVg/dpW/ONVr40vocrlS0daTfDtMXtBWTJW8LnHTvbM0LyfpErPwHF/EOvW3Vqz5XMNiR5j70k3ECdwsK2bf2bF3O1q7FfE00LQSKB7q4opF6OH86FdNpA0zkWNgJTsIiTSonzDjypri49LW7mIc8SD/RwmECu7yA0rS5wph84tcLCdyo7ZfbrtoQ+ByxK8aRQdARw1oqaSHasQe1MXBzQMyDKA2jgav3uMbBdyjRxjoceTa7cpBlLQJXjnK35uJMwJqjLOnCmAM=
    username: AgCR4YufcxNVzESg2rlcN73rFY7D8svwKeLSK5YWiFKGiHQaWYi6Nry+fx3Wog3WHUQKp7xmCPZwYUkCXYL7r+SbNasuHoufHYT5Vk4vWNjXoz3JW5klAKszNFuy73OoeUu9Hy21jJQIeOR/AxFwCSOtfATqS33Zeh3Px4wnOD870l0O4TKKCPIZ9B0+jgFdbkK+6rm/Dx4GeeXmadlkjy9bdIJsnDhMMxJ++YojKJnuE1sLC+aYt5Nz9q5ftrv10o4QweBatVOEfxlFn80+R1oAo5j5JBNO+OjmTO9q/41KNrWYwf6TKti4gYtRjp6ENNDw5krh/VA+mjnRFAeIj4bE4iS3hO5+9o1totkbHI2EtQtlPBLDulwLs/ZU99aS4huiZMV2kJWrXdPjGIrM0OK+owAysFwUsGdxqEeIpmOWYbTDuILnHj81M7SISoeJDvi6MhTohS6rEsV51ZUPRuifDVCUI6SpjqC6T9OSn5HWEGReapg+Rs9cJo8UBiO8d5Vhwtb86b3xxnE0YJQtjdz+hULuTSM5Jt60TrxBb4HCvcOWNWWe8aSw+y1lflqO9q+jHaYVLj/Zq0XfGzCzyrpq/rEWMynN22qTdhASCZQVHhP/AXbfY1n6TMbPvK6oOR5tbeJLLYjEfgZBT0bL3mObuv5NX4lZlulS1Y9kgBImxCvSTLK3zD9DgFUulX9p3EOGy9xf+g==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system
