---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgBeYEh11+EMv2VlRkl025jVra2wvD/GpTgHUOoilDJ4NScBWYpZV2ohYQqggm9BHvRv+8Splmv6D3kOD/bZ2d3W0ZEnewnnfY9VoSObsWQ5TZgNGII5dutfSijGwjvsS5ZdrFJDhnq/kgyx/Bpk1dn0HD00SY1B/Sl45XeMSkX36he8kfvLshcaT+XfjbHhDl9u5Q7ooLmPlctChDOMQhl0kWudlDk4AbHmIu9IqxhxwR7woJ7aRbH1afIcXdHmDXL/K8v42NawuOKw4hprc/7p7C0JmYftUT8zI1g8Q9F+xfED28BGsvYtkKKe9wiFSZddpqYkHBy4sRURXeedOfr6SHqyEcw1gLzBpio3TWWEG5SP5bV3Ed+cPKc7EmB9+edfCLx+LWmP3K13C0nX+tDbLYQe0bkQyqz+gmwkzWfBTpFr0oSlgBwi1VY6BQnNz7l94F1Dfn0gDsll6BVj4x4jy1KRZ33Q59RTprbFGkRcDR/x0PPZUfXACeiVWC6DydKjglpmJNS6Im3vcjtojbEbg3Hm2AGpFFTGY5/sqf9uL9GHtemMma1zM8BzGnVixHZkany3ZLvYzTwqoIMm8aG8W8pQ29N1/5cXGXwLqwXc65joXfFEOXPVUjChaZrRawRmF9TJKUaYTlNLk7Rr/mJRTSH2ZVpVng6dOZoIMlEwtqfGaZEOL9JJKppS+Y+rBMcdIiW7o0Pnqw1cN6lRWnxZmQaS8FxReED7wxPD2L1gxinZtL1HHVG+6Hz4Mag2tIo+10knBJyxC7KAT14=
    username: AgB4sWrOV5XmML0dJZyWk4kSqq19Am2yRdEy+t7tLsHJfBrvfBhfoZ5Ql757WdaNnXt9bb2KbXXRtdlIuFKZBUQsQ6i/6J7sBDlV13Est9+aG8UJblYZt8ilMZeuhWNmo6cRQYAdtSP+x+G4snsJIuDlgJ5HPBc9BoeHonJ9SXbj80YsI6lEjF3BGIQTa1fNrnZ5T6/z9ygP8SrrcfWFvUAXi77J40iMs9a0dw6IRT+nTDIi+LxEAoLcnWoXaZhOvaorcshnVD8D08ueEIuDrIwx6tyzYwSmuEBZYjjuDGinv45IHEt+1WJwFLZUwRqAOT6ShJ72c/bZhidrQN17x/7dI0cH6n4Fo3eZ8FwZl+dmNzwDCjYFS9yUYpBlJfz+7KF73bfCXyDAMd63DZQANCIwHykQrYXZ6ZM6q7wfsItJJk+XWrmEGwGL5PzGJ0f3QXKn9Xao/FwwlO4vCoz0a02YjZ7bM0UoIwShRnO4psks0xsIjLY+16DKNu+hJA+mqjVym9VXoKLmgxH0DRMgKZuu4uZvr/SrvpGErjTnmy/xgp/+XK2KVOGdlOVlDheD8qKhd3JyNb11Qk9PuDEf7YOdrIs4b5EZmZJyJo7SYEXQF0HWx4PIUHkK3Q3pmwna1GJVMnR14EZVG+hMwTSLVqcahntVE2Fluj8r1m6EH+wLluaPLjpwCuVjpXqTV88CgJVQw2iHpA==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system
