---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgC3HKeWP+QCj0Ek++P8i5dZ4DhdUe40hiiamHqViRJnEsH11zEZto5nrS/MYHxmga+fscfuY22zDbquG2vr9bDwhES+fanD+aJUsTZK0GgKQ7oqNdzVuvLwVoazxmz5TawmgEgSLMHtpWKDzL+5S46Mpe3Bn6J/aCh3iF/ESmgYQQ/uIHjjbAh29OOHYaUwPw7faaG67ne1S3KY0S7wnx0jS8hiSJec58mTG/U9ZWhrfPjJPoYhIysAaDZPlEmrTua6re2eXxKjCdt3qRzIbsyvIBkGUZM/g0XZC3A1HeCctJW069iMLc1griGTDOFZH6tR0+yvUJYa8TadkRgeVmbvggombZBpynESIuOa+Kp01GmmSvhlZfOPr0rfz/pV2t1udQP3zszyc7sfL/MElnqZLdHDirgMcVry3wi5uk1hWeev37/LTow2fY0OnrudkmA42C8gpASvSeGEGlJQtosUNMBG3OOwPlEn7aF6RoUxGM0LK+q7mouMjBqbkrXopJGZ4ow271n/1kXcU9Ac2U4wvQXD4yy0KOuaQ3n8yld621bTDHga18sZjDYs7IYin2q700WskXCQST66ShwvBU0YE1BqbPDELKLXdq5Fu9WbPaeEeTGn3/ima8NqC1q5UttF4SqrJeaUpGLDaIyKtBzRiw9LBnu7KUHHBPiS4VF4JggqY6sA5VOnoOb31zvdfh1MtRHsgp1/BVwYW4aONVXrtjYin6bG4hiUP+XCRbUx8qrBkm+c+OrwHQi0T+ccg8WU5yyYOVKRYPCJJcI=
    username: AgBNKAwi6LGNqU9Ag2ilOn2DgaYvYFclaT4FuBGzuXb0A2dIZwL9mFe1rvxpVfSs5/Ba4uVfOkWbbcgiFXrFq9zSctUc9n/7Lw6HZeN7jHPtO+URW8/ZY/1bGLaY/xPnm0uzYW/6YVG3e+OSGomO9wankF5RuYlT0lZZdsZ1jFcHWHFCha2Ox1GV3f9Ko6rqwnP7WIJzCbGlM4CNKs9zvN/pwUpWRsAu3ILLv1gAH6f+x0eyFjdFD5l9ZVT4GOOsX4C8iaG+0HKyTo8o8CijV+PWWP8s9I+VcN8IHxaRmOcvrK2JirX7bhNbyYxaLsc78cDTHBEH8/CJEVlQ4MxqNsLiHC3oBrdj9/HvlZl6cc0rBAabpNnQDDHY2qfs1q+5R0+0OaX5a3ioDQKbYC5ROeEOrWr3Tp7U9MxKGp5mIWSwQfLboPCcxtbizSLCDJD1coxKxrtONBk3JkizsDQcjB/sfX81/jGX1y1fkahkM5/fuFe3lvxXYt5Yy93e8dkRmx3/ZR2hRpaHuuBKbFGWv1NraO7igt2Cb6wrlrCvpwS2XBHInz1f7IcMfBe0iYdgs/9H3wbAVxpJ/KUmrkKMTxjRxKuRJ557DcOkiq4vuU00/OyTDawTAvxbCI/jaO+qcUDJyVOa7e1/iJpt8vfJuGWKrLMdY2cpyorsqSnPNvhRhy68z+79oGjqxoH4oah00fKLrvl2ag==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system
