---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/blue
  prune: true
  wait: true
  timeout: 5m0s
  postBuild:
    substitute:
      CLUSTER_NAME: "blue"
