---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-sealed-secrets-controller
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/sealed-secrets-controller
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "blue"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-cert-issuers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/cert-issuers
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "blue"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-ingress-controller
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-cloud-controller
  - name: infra-cert-issuers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/ingress-controller
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "blue"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-sealed-secrets-controller
  - name: infra-ingress-controller
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/controllers
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "blue"
      KUBE_VIP_IP_RANGE: "192.168.69.201-192.168.69.209"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-cloud-controller
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/blue/cloud-controller
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "blue"
      KUBE_VIP_IP_RANGE: "192.168.69.201-192.168.69.209"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-sealed-secrets-controller
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/blue/secrets
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "blue"
