apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCei9ag6UlIwhKnVj84Mxbgu/qJyz4pdgDPDiArN80B6kHbSjBqn/1dubfpbPjUAykZdUG+ZgH2tqlwIgJreqWyoMGus82iH+IPpI9mAZobgvnx1Pl8g/oIy43Vj9jQ+AAZ8zCujzuH3x80SGtOb5No0fkEDXF/cS/VQqcbhV2OugTla+89K/4EzBYr6IwN2LP9VmjjdDM4u//AlssCw+MlU/JZwC25WVsncgAbShjznjyDG9Qy2u5A7D9NMnivqwXRNFslsNPoTwQ3alMr8ljUueOjQ9zaGrYeVw1kc5k8wzn1FHwx7c6dSQw8T1WTwwYFnc+odbqt0L5YzQmdxMWhTnS/YWRwOtXHI6NYIipfXnafU7Zf5xDgR2kL3EbYhVrkrE2tCoJ1RpdMNGGpqjlu77fhrBE9zdYLk+FdjPZ2ZjM1lEmVU6vX5xCbUWo7FPD1zunH0NG5Jmua/32ayb0/PRVQ2anvG1ZwEhTPTZjgoNkZzsbe1AtB0OgY8TA9/3dHeLwFnhiaxhaw+qsXGFxCgI+wAl9Nam/Zr4besN6A5kWG2s1SCCswEO0T1Zca/BkP0NtYq0ogD41KGfMErfhze3ZIcxXE9kVVDGj7Y4eVnGKRddlurrzYFvKO3Mf7LCgqzErUQtI16shUNb/ivTgeFPMWMMISczhO0vIFHieyBUxs2zEETDKmALYG2/N7gMPJObXHJinNppQXAc5quWgcybYp41t/GFqSjDMie+Kq4Xr/ZmNuDdw0
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager

