---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC5javVVJxP37cQm84q9tGF0h2cbr6cuebZyjISCTgbYJP3OwI9Xa3++0aGF93pqljATjJP3yVwbbHF6ytwJk0Pnr67ttG8C9YBml/q2/y5b/vAu9iE8e16u4RHmWsnxshVjAXo7Ii/f7UVrQJxbWjMiy4yKkvPbTS98oKzGx3rVlDykWcEwfj7EEM5JA4fC03M4ZVEKB3VJUfo2QzmAnkTabzuY33W8+MrTYgVXJgsBo4nQuAoD+kDdN5E0EY1AqgDDMVVW3eOKtsfHQcRpHGWBFw8+xC3kthvImUn94LqIkSHUkT+J0s7+gYLUkGbi5xT8if8U7HmANAvsnXFTB0eHLA/1kXhBxDLbsrEQ49q0/eLHm7O8t8oOze3P8gzJ70PMNyB03ueDxsEcLKE89jysBdTbtrDp4gYZjv+ajyP7dT6NR2G/hNV/hwy9eNhZwFLI2L7KtrFC3zlkUhoaCtgHoAcdGAXTZDAsT2Vbq4YZN4NZ+Bx89jh88GHPS6yauE7gugD9e2sOZkiRWH9SChgKaAjtviMpTnkez24/zn5DNSd3FqAmJ9rSXssFhuzttHCd0Os6QiQom1E98fJeso+nkFkatBvJEjDyuItuKJZ9LDyrrdLlzaJStL2N/GorJ4otGPw3OR3cZbmTcKC3KySOyWP0i6W2vTRdALob+u0KtfnYmTJ98b189rcQLtn4MGFidII2fPO1P75IV0lTOqtpPnFEN2hs9G6JrPw439arNCgdovZQGxv
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager

