apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA6FPeL7hgPowtS5ukjp9chYfI6FJ5Sgi2AHoqaUR09+q6PpnnUEazdLOccgsnRrU3jy/n5TG6GnV0GY52Kr1/x1vdu3gMgS2oSIT8RMzY83Ifas2dwqVE87HJJS+P+flbMoV8W+aMOI1ZxwkYCLpgTme2FOpznyTXs/86FJf2pTtpPV49/cJN32FOhZznbDKMkKGW6cFKCbkRsWNzscGC2CqZCDdBBmJZxeDdY5wyEpHRjCddRI7NrEldsyCYXUJumWoP8FbKUUZ40pUbldiFLvrXKWkFA+Udj7ikBS8A+9tJ6/Er7pUB443s4CErjaxn6m5Qgs8gDfXX9IFV/kwd/ljsEnNgF7zJj6xrGMP0uLSto+IST5qPOafVZMswGVqmCq1SiFD+8jdEdl9iFrkqjCpBktGbDRLeaoJHzcDYO42WAyejndcCyWCAhruN7sZ6u5QfidTE9RyXcbV9AWaxqCuq3CFbg7hqkkGyVRqinhWj/0PYlsOQBBNpjteC/NLTot8jL8I5CMfJQUo+Bo/Lf//caVQYgRByw5tHfopiycYpDujII4bVIa4Ep5yHjJGjzkDA6ZoYJGPyj6UGvMt2GfyZ5rXza8gCiAOj2uUe8OfffzeZB6bL3zvycCXb49SOQEV5XZotaO9zoX3rZZOEoJ1IUeOo1Q+g+foq2eXtXTnOv23Pw60ueeGP+yethLIRe7M4BgVpMt0j+2UeiuOx26hFsQ//5kYhd+ph1QwLTmgl/DQ0h7gbG
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager

