---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-stack-grafana
  namespace: prometheus
spec:
  encryptedData:
    admin-password: AgAgnCS4wVGRRPYkq3Q8Va/ZnRXc6cE+SDg+44++s6BwwS6JD+4fr2K5vrfMWbFBW3s5Oh2utLVPpWhOHxOy+r971IWwAc1LSxLN9lDKt22mY25D3+dhV4UOxgSql63e/kUYXtwZwcDhZQVm7m/PMuRb6rYRd10tm7DZCsQ5HSA/En/VYkvTUDmG005VbD79mhoeryLB6ttUmO9GLuyoF4xvo3FVbmLgaJ6+HrnFWAkCf4Gn7NANjVff5SylFmqyWRO3a7wxJ5cc9KoxzsSMGS+wfoQhVQn4a7B4IasI5Qh/tKjF0z1jI8VOgUE+LcMVlk4oxB+/YOAFBeZuQNC3Tk/4IW0wemJikTehDa09pTg+DD9ux8ETlZFzqLxR/tZav0FxhmGlP9po3ZKPdwo2GVUj5LmxNMuNzEEpKhA7ZV6gXZepKF5QEZ9TfiKwLRueaqrjmjyBFLZoyhTuvuk+esouSjI8HtrS9LBU9JlTjidbVOxSW9IkaNJ+hOXiOK6jv+AMwBr2615RxAcgp5swIqd9EM4wLCEmfAYydPH6ouoFFBkrwR08CDjepNvJflTPIUGnHpW1MJX72NMJSgVdaIeWcWV9/Kr8QDwA9L3+FXKSRy5ZHlYBmLcI/QR9OEElxL0NH7Je0ts/ODieTGtTfoHlQID0vlRb4D0glCuGu9JqTBnu1DbuWWAapergWcKTvimkpmTYkdfud+RI8Q==
    admin-user: AgBUeQiAPQ3YIiASuMNsKYfa6Fg+nbIPq9EqbJx/1RhIIasp66jkPofgL1Thtd7T1boBagh281PIBLFxRDsYO6uyHR2ykJXvj0sI7alnGh+kQloEJ/DnXNKOF9PSF8R7mC6t6MG2i3LSfaN6phPe3MH5Lh+rbJ9C+AZtcdGLFVds1+nbxPY3jONkzrV4MhzI3WWRJZ+gV8iO/90EZ6U5K02SpkLIq0Z2xCejLXzwOrhJxIXNV2iRPyCoA87uw65Vrz/NdZp45S7w+W2rvMLGv8k4mNlF4HzFhK1m6mWTxXhNvyZIxsrt0UqxXCo8bTYww/Js62yceFHtXWidUZNxTu7EIDDKycb+G/870vuGUVpHLaCdZT4s6zGpJsiRhMCi/qh7Mdr8eD8NsPFKyHWIW0PxPpCmm96p7EcCetzP5gVnWomqxRvuiY8141Truef1gl0TH4slUS8N/hOsxtKqgJZwHbzKBzWRgg3jyraLMyOdzHPjr+cjtCEq42iTVcNbs0b6cU+7UtPxdMqo9WwWbECh6ZWH6a7ZFuRChTczWgedzxmIKOJtwoQuKgLZE3fd7i+iM20CFP0UKKqGdSZbQSt5p8WDtx7hSAW6CSEXO6lQJT71Jt+2QgCTp8epXno8PEsLYHGuRQHKkl4BdRupb0WXgxmqri6yvEmFCCOTvBuMOK4Qzy2uGv/lh5m/3P7uhrklBAo63Q==
    ldap-toml: AgBssYxzPd1Gt6sCrtr2mteh/u/8k5fj1k1AWB/L9K/WcxV5F1AHTT/HJ3eBnHQKUXJKi9qTKcEh1sXswN4kkkJ/6XlXMDDLvxj8Hr35BqVKohjQWr28GwETj84CFK3+HX0bfILZO2ZTY19suvuQH14zUZe1ubdo/6jYBGfGD60UGwzQaahA5fCOLd25GQzrJGy8piYzZiWIgdDHMQIG4KvgUNUPR9lr3jswaIODwDHBpqiWaiys9go1GV68rUVlM/erWlTTqk9YG6FxCzQnTSCiIpkxmwIVAdLThT94/k7+6P6IA+4ZE6GCzLEzodJthGGp6biFa1PSHCJlxHi4wk/pUEGW1mJsKyPhmesFJcosgJcXyuyYVRnKCh96opyMJD7r1mF9euva5nUZbyI5hHsWSYJbQ2yfFE88KeLTb0DI63Ztjc8jgICLj5Uz9MQBat8t+O6aR6Qb6607qJUJ7HdVrTpnBxivePACS+0E6MrRjfd0DOd6Wv1ebSK8e1398j4ohaU7dbrQo7tZVol+txHgK1K9hI389ZhbSHObhHNyMrATYS89R/mdXubCaYBBdrqFA2TaEpkicnNlkyOtUMId8k4nCKTv30blxMttvFMEkbApGOl985Wxoom2lT3w5sUfqpgi7RAABdWAXonSyWb2lGXneYon5vvqHmRxr2PVTYnWXXbSDQWJW+blTdbcpNQ=
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-stack-grafana
      namespace: prometheus

