apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgB/nOBnDYRXkVNi8OcGWjzpRjvOpWixhsvP+e2k2Xcx238e1HhIBWngsL+AK5bqERMj5yiL2I2CgAglCPyXJlPQEbd5qattyUZiwmLTWICoP7hrEuLmn4VgYCmDKdeAx1vIjbSnXSgKL5lE/syIa4+gTYnLcEMFxh4zXPKAm7l+OVr82JHa2bs6emGzpaT6XDfpMm/l9Hv1AuEa+yXSgK4lz10S2Ropf8bkemagGM2jjPkNO3XqED95/FEHv5ORCITSnmOSgsBmIGzdmFpBhe6XmgnXmjHsxjoHNH2WBQe/nSFsMtxdesn3X2uKXjkp4xv3FyDInOO8KKQFULFN2r7rLas86NRPnJDXBrlvYaTOke9TopmcH+OwfbBLIv0ZKlp3XSxL6uOYTZOJ61IEANQTtzK6ETybFFcikrVHJqGGMe7FXvDGkFaPVd2kJLe9G9YM2ua6fFRD3sNltl1QHmznGFj46P6X83TRg4veogz4DQMj8Q9thbN+oJwJeOmLK46PSO8iMi7n1B4TJw+vT09dWGOsHX+uB2yKmvRKLvYn6/fpOD4pjDAnDrZwv6c1ilCCmEES+EWwAXmzprslCZCHg6tSVyGYBfvXreQyCbBu7Cc16GGRwqk+tJ2obFRb45iQCqRUZ9lqg6/n8o83KukylljJ/5eKJG2KDUAytKMj7Hg/BU+OLLyOlDDcMzSxPS8K3GTnWrzeG6T/Ua1KvWwRKxWb2C+U7HU7aX3hri75kRDXw4sIHdH7
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system

