apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgB/Z5A4RtOfXPgmT1X45F9YQ9PUe5O6jZ4vIfThtNjGZvzuugeJRq0T6QIxtpk5CPuR6fRqbJg9N9tWzmYVVeBEJ0+R0veuRFhRLNbn9RdI0OX7qk4GvLrztOniDsC0WmxCMmkblCBIYgiGpU/jvC34ktTfI93Uh9d4rLzcYIr9k0YmYrzMiS88qabS4VTsgaTUQCCHnwL+24cVnlO+rgLb4inx9a8Hj5PII7J7o0RTeOiDD8b80riryh7hp1W1rZeLo77/lRImlzGktWSxJJmhFC8I6w8Qsu7Dex87uBAeYPS9jlt/J+rfW4kmbYXjpvnSpzN2ZXkhOthUdSHZ3k62W3C+TKXX5i4YEW7h4/h61L/zF8sUc836ciyNlIYdvzCTyP3tagV1viP3jvPzc+bWKB5/jNRm1qvpMYApfLAdk83Zh0PTpzf/YEzLsNusZ4IxNEbYM6gUih2aSRTeMdhmZMD61hqWGj3yt0DtoygmpNk6RqyUw059EZHbXyjMtm+HiXZiSvhYMi0gcpGkswXdScyD22/bRefe75ZphVDp6qtDIL+k5R+Y7hhu7hYbZ6cr4qtiTT2ltcdgo9HQWOhkC6h6h8pXpjaSLm8h2yLzsth6iRjzDwGeZ9o3JIPUvJdgMlRuEe2xN5J6P6zssZa31Ji4+xaIReLF2tkiPDj1vB/n+Yr68RGQwjkrF1TeN+R4D9Tpc31JLuLcXPYZXvp13kxsP3kkj5uwX6pcrmfgQO00up4XRgrSE40Ue8aIExDIhA1winiprZjiH5ke44EFE0On0TeUgti31O5I6WcL
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system

