apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBmGJEdJWJpF8+Hvmv184lYiLJJinPtdDCHO21ZFLBVfScLFJoywH4IYLNHBSn5UTcwnJGQ+b5Xnlj3rFvphXKGTzQrbYbY5ZOVAlLwG7wQ1QCLfqgTNyC11uN4OpPxgtnpyj01ewmDdXYf9hW0HTxUhGqqNW+6lUJJ2H536TPZgedLDLMyrL2oqBhNrOGetSu8XzJ+yU/6Ac+2tymJg32EzQ9J11CiR4N3D4oYvZDTcBDnYr2Be6FZzT2XBn3YVo1YD5WemKAZcpIeI4rxN8RPwdo7ErW/2mSc844ZRo96jqFGHpsqS8E3CW9Ke9ETJV4G54cF2D3gF+dQjQITNeGhoEhLgGFkSOd9SLqeeX3CjM1eH0KiUYphbgyohSmG/L/5VZ3bqePre31MW1bG3uy1Ut5V4b9CCo5+rdohWREJcHZ+f3Wk4F3hhI26+TKLe310lzCdbXnBvJnreXMPMibXDJi5BwbxdJgFhpOYX5m55UxGSr5gZsRtHyVOXTlMnV+PtPSmbsS1V9IfnXpVcKfS01466R94DqrF8fcnyJZz5vcvVImTgOmTGjTrUkbEsjZ76iHgmjU6Zqi1E6dW8ejVFXR7fjL9VxmpqBFNqZeh/cntGtTHnOR+0yCyztBQerxW5UeqDYJ9FeB/izHXG8PDMpMZcqNmWZUId8QQv+FP6gQRFRRbnEx9INp4DGi3Glxl1w+AKLnc1XG8U7skKRFj+sUPMg353gLLtBtJaZCFZR9bgTWCsYfI
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system

