apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teslamate
resources:
  - namespace.yaml
  - grafana-admin-auth.yaml
  - postgresql-db-auth.yaml
  - grfana-repository.yaml
  - grafana-release.yaml
