---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: teslamate
  namespace: flux-system
spec:
  summary: "Cluster: microk8s, App: teslamate"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: teslamate
      namespace: teslamate
    - kind: HelmRelease
      name: teslamate
      namespace: teslamate
