apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate
  namespace: teslamate
spec:
  interval: 5m
  chart:
    spec:
      chart: ./
      version: "*"
      sourceRef:
        kind: GitRepository
        name: teslamate
        namespace: teslamate
      interval: 1m
  values:
    timeZone: "America/Los_Angeles"
    virtualHost: "teslamate.dimitrikoshkin.com"
    envFromSecrets:
    - name: teslamate-ecryption-key
    ingress:
      enabled: true
      ingressClassName: public
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: teslamate-admin-auth
        nginx.ingress.kubernetes.io/auth-realm: 'Login to Teslamate'
      hosts:
      - teslamate.dimitrikoshkin.com
      tls:
      - secretName: teslamate.dimitrikoshkin.com-tls
        hosts:
        - teslamate.dimitrikoshkin.com
    remotePostgresql:
      secretName: postgresql-db-auth
    backup:
      enabled: true
      envFromSecrets:
      - name: postgresql-db-auth
      - name: s3-credentials
