---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: teslamate
  namespace: teslamate
spec:
  summary: "Cluster: microk8s, App: teslamate"
  providerRef:
    name: slack
    namespace: flux-system
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'teslamate'
    - kind: HelmRelease
      name: 'teslamate'
