apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-postgresql
  namespace: postgresql
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: postgresql
        namespace: postgresql
      interval: 12h
  values:
    primary:
      initdb:
        scripts:
          01-dkoshkin-superuser.sql: |
            grant all privileges on database teslamate to dkoshkin;
            ALTER USER dkoshkin WITH SUPERUSER;
  valuesFrom:
  # FIXME: how to create a user after the database is created?
  - kind: Secret
    name: db-auth-for-teslamate
    valuesKey: values.yaml
    optional: false
