---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: postgresql
  namespace: flux-system
spec:
  summary: "Cluster: microk8s, App: postgresql"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: postgresql
      namespace: postgresql
    - kind: HelmRelease
      name: cluster-postgresql
      namespace: postgresql
