apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-auth-for-teslamate
  namespace: postgresql
spec:
  encryptedData:
    values.yaml: AgAzIwAHDeMNVyjy4f2ZRnvGD6Gj/otIJYEq/EavhcJuYVaTQhL8dOgT1eeENTxYE6ZXOI4+fL3qSUknAy7VlZ+YU7zYO1v1wwhSbo/SfbUk/adfeoq/Xr3geiSJ22LirKwOtPLGvJhb0q2QXInQpTcfpHXt/bdIDEOD35zbPly2/WL+8G8TEH4OrCnskF8P1iHxwMVJQnvCV3Z01whbFnwdHlC6l7f2hXEBxYAsllJJpvvDngI5q/PRb333tvDhnAhM5kmh2dMopx6XGT37/viMT0V24uoUU+NroFTSakEiX0ydPUR0qBxfGHhhan3c1gru3DnS0p9tPS3qq36z3JeSbsw9r321wt4SPgKrFgVqgbTHKUFydTKIDV7xZ/ge4YFD92QApL6678iuGvFSy9v9jx1V1PQOW7IodZVmd9pkoY8z8lkcvA837bTGCsXycGviQuD3EmCtVou/5BgGHWhFxG3VJcAJ9k1xGcZQ5dtVUsae3utnY+P2s6EJc8+yAY22SAy4iG8Lu0AaB6vuHesfQhaEYg6+uCoeI6FRBuJuXLnBl3wURpJHlv38TS9UBAS7Smq6dCb/ec+AzxEL3V1nBzKwMoxX4zDKWwA4OuKXizZxlGAmDKVDmcd55u0QKH9TicqXXQeQ+DBaVGww2diJt/Ezj9TmcGJ8UHysPchEPQThcdfBH19hQc0W9EwLlm533Fssp4G0a/zd/rs3kUO74J3HsTnDb7rsKtmi/DvhMyvN+vvVcy4wtSrejwvdQ071NnCYlhzl8zQxJ/2FkymI5vYBkcgajJ0k
  template:
    metadata:
      creationTimestamp: null
      name: db-auth-for-teslamate
      namespace: postgresql

