---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: view-user
  namespace: asp-fantasy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-user
  namespace: asp-fantasy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: view-user
  namespace: asp-fantasy
---
apiVersion: v1
kind: Secret
metadata:
  name: view-user
  namespace: asp-fantasy
  annotations:
    kubernetes.io/service-account.name: "view-user"   
type: kubernetes.io/service-account-token
