---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: asp-fantasy-admin-auth
  namespace: asp-fantasy
spec:
  encryptedData:
    users: AgCtJc0VLv6cVInhaBB7ajx+CXhHm/siv7fr0fZ31rH3O983yDnUlH5g6dnXmquQZjrYa+Q0MIRE3/Tzwd2EgiN2SfmYB4tNDFr9oFm2IewLprQ76JIyEt2MbZVPGJqD8R40kQ30y2cSY210QExtHbsYrJdvlykEVplGgPDRhej6MELMhDJkhwwyEHjplVtbxgmuRox2UjuLpZbbvO3ooUMWCaOakxmF13kz98UXLWtjDzRwHJLc7zKn0ltkA8IgchmIeSNrhW1tKCevf8Ygz/+lvdA/lQftl5QuR7kMdEnlT9cfEvj+91jdHffVNx/dK+7JaGa92/0fiagoyx/LobaYmNiGsrTS4VpYVb52igQ2hBrCFYAkQ5CBLHeIIL17tPwS61VZcexEBMoX8BclD+t91RonJh6pLjVSNmhasXTIFXKz/ZpH2PI0cC2mudn6Q47kIJxWFh9opgmn+tCRcJzC0BGNvdBkUJAB1pEN6a7656xOrXnQf6For9WuxftUt0D+Cx59Pqc3GZeSacXkJn4QOwe4jIjmc/Ca+P/P1QtLCzrNdrMBppPlPjHIeyYM/gy0Zj4LNx8h9pi33KEqZfUiRR4hYiLKU0KG14BKH94tBps4BKtcX+Q/cjw/Zdy3h3sMcGjaBZ2dOdV3Cl5wCl0la6Sp+GkHO68b7M9icK0xhF+HitYOFOHgwkq1OfeMXUbVGz7/qEOr3t6pJUqLVHJsHw2sdbkFu9An2Xmg6VLB8i7yiv98kEkDQItixetjubJz/PqRHhG8tGdfOXRE7oaVmZQ=
  template:
    metadata:
      name: asp-fantasy-admin-auth
      namespace: asp-fantasy
