---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBFH66PIB1ckH6bjW++sIAo/nmvWFs1WqJn1gCivmrza7QaSRzagNnBXvh9NCxV01IEtwnybVHuOjEmgow0CUlUD9+1BVs6g38qBIQBiBVWvqJHF6h+tQPvE3atDG85AdHAAnyz8N8eVJvtthAWGVqR+mwkw4YT6EtB9wDEqNrlTcUVPf7NTJxzNPYhOnXmQGFz3QShvA5dTmMG1Rc7Ewj5BHmm4EjoM3ex2FJc7izhJfnN+08p07OeB4PYdXLzDHDeqyJyGY86DDvYWedgmiFMFi0F5Bra1Uq9yrwV1oBKrJQe7WOuQsDed1h/LQGo+5kUKXPz6KcrsiDx6mMFVkVTNHrAsjG/xvOxWZFe4JJpJL9ZAgfb30qnrC1/SDaQCqSsLkpQj6mLG9xp9WE9BHI9vgjcHB3xJvIcrv5hWYjEIsqonjp5L2kgA/2f92FO732cZKooceLItZpZCDQndd9qpRzX/95OFa5zdGXBch0K8yp7NjIWzoHX0D85plh1Jf28IX8Bo2jqthPl+HQnJ4m3f5FQHVY6gQ6YTw+zdicDY9wKUXRzxaHq7KpHs3O3jQnHdgtLdWNvYuKWAKepHCxYjiRXcW3hDdgAQNvB1dFxOUrzHaUGEoJKmaRcJl4dNEQuTqs6rbeRtj76CZCZ8qqm5JcPT7e07UbR0wMmcoW3DUtBZG2PK1KMWamayfcYMD/UB+ySI0dEI/OeVF7Y6W3N00vUrDBQ9xQxMXv0ZdZH0jyevWNIK7pDBEehMauMhMT/3ygLD4NQBvHuGf3S5VwdVLzKhqS3vIg1AkLT8EfZ3aj2YU7nRnZqg2zhmk2NkxypO0eIuJecxj66Y7xel1Tl2WIBRGn5EpEQxvbcCucqhAk7fu05JygrXTjsVPqhxxbp6kDJ6CwtaW3mgmapT5vrEqo7e+Bn6gUodryTcE7uKX4mjjZDFbDy
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflared
