---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "v1.14.x"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 1h
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  summary: "Cluster: ${CLUSTER_NAME}, App: cert-manager"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'cert-manager'
      namespace: flux-system
    - kind: HelmRelease
      name: 'cert-manager'
      namespace: flux-system
