#cloud-config
package_update: true
packages:
  - qemu-guest-agent
write_files:
  - path: /run/scripts/setup.sh
    content: |
      #!/bin/bash

      USER=ubuntu

      # Disable password prompt for sudo for this user
      echo "$USER ALL=(ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/$USER > /dev/null

      # Update all packages and cache
      apt -y update && apt -y upgrade

      # Install Docker
      apt-get -y install ca-certificates curl gnupg
      # Add Docker's GPG key
      install -m 0755 -d /etc/apt/keyring
      rm -rf /etc/apt/keyrings/docker.gpg
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      chmod a+r /etc/apt/keyrings/docker.gpg
      # Add Docker repository
      echo \
        "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
      apt-get -y update
      # Install the Docker package
      apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      # Add this user to the docker group
      usermod -aG docker $USER
      # Launch Docker on startup
      systemctl enable docker.service
      systemctl enable containerd.service

      # Disable SSH password authentication
      sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
      # Enable key-based authentication
      sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config

      # Remove packages that failed to isntall
      apt-get -y autoclean
      # Remove APT cache
      apt-get -y clean
      # Remove dependencies that are no longer needed
      apt-get -y autoremove
    permissions: '0755'
runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service
  - - sh
    - /run/scripts/setup.sh
ssh_authorized_keys:
  - ssh-ed25519
    AAAAC3NzaC1lZDI1NTE5AAAAIIhdsev5Ys6TvGTrc1Vhk7a7fAu+nCud9T1RVSAgnWcs
    dimitri.koshkin@gmail.com
