#cloud-config
package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - unattended-upgrades
  - update-notifier-common
write_files:
  - path: /run/scripts/setup.sh
    content: |
      #!/bin/bash

      USER=ubuntu

      # Disable password prompt for sudo for this user
      echo "$USER ALL=(ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/$USER > /dev/null

      # Disable SSH password authentication
      sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
      # Enable key-based authentication
      sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config`

      # Install Docker
      apt-get -y install ca-certificates curl
      # Add Docker's official GPG key
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc
      # Add Docker repository
      tee /etc/apt/sources.list.d/docker.sources <<EOF
      Types: deb
      URIs: https://download.docker.com/linux/ubuntu
      Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
      Components: stable
      Signed-By: /etc/apt/keyrings/docker.asc
      EOF
      apt-get -y update
      # Install the Docker packages
      apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      # Add this user to the docker group
      usermod -aG docker $USER
      # Launch Docker on startup
      systemctl enable docker.service
      systemctl enable containerd.service

      # Remove APT cache
      apt-get -y clean
      # Remove dependencies that are no longer needed
      apt-get -y autoremove
    permissions: '0755'
  - path: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::AutocleanInterval "7";
  - path: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}";
        "${distro_id}:${distro_codename}-security";
        "${distro_id}:${distro_codename}-updates";
      };
      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Automatic-Reboot-WithUsers "true";
      Unattended-Upgrade::Automatic-Reboot-Time "10:00";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service
  - - sh
    - /run/scripts/setup.sh
ssh_authorized_keys:
  - ssh-ed25519
    AAAAC3NzaC1lZDI1NTE5AAAAIIhdsev5Ys6TvGTrc1Vhk7a7fAu+nCud9T1RVSAgnWcs
    dimitri.koshkin@gmail.com