---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-upgrader
  namespace: kube-system
spec:
  interval: 5m
  url: https://github.com/dkoshkin/kubernetes-upgrader
  ref:
    tag: v0.6.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-upgrader
  namespace: kube-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: kubernetes-upgrader
  path: "./config/default"
  prune: true
  images:
  - name: ghcr.io/dkoshkin/kubernetes-upgrader
    newTag: v0.6.0
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kubernetes-upgrader-controller-manager
      namespace: kubernetes-upgrader-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: kubernetes-upgrader
  namespace: flux-system
spec:
  summary: "Cluster: ${CLUSTER_NAME}, App: kubernetes-upgrader"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'kubernetes-upgrader'
      namespace: kube-system
    - kind: Kustomization
      name: 'kubernetes-upgrader'
      namespace: kube-system
