---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.15.x"
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 1h
  releaseName: metallb
  targetNamespace: metallb-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: metallb
  namespace: flux-system
spec:
  summary: "Cluster: ${CLUSTER_NAME}, App: metallb"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'metallb'
      namespace: flux-system
    - kind: HelmRelease
      name: 'metallb'
      namespace: flux-system
