---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.4.2"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 1h
  values:
    controller:
      updateStrategy:
        type: Recreate
      hostPort:
        enabled: true
      service:
        type: "NodePort"
      ingressClassResource:
        name: public
        default: false
    admissionWebhooks:
      enabled: false
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  summary: "Cluster: microk8s, App: ingress-nginx"
  providerRef:
    name: slack
    namespace: flux-system
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'ingress-nginx'
    - kind: HelmRelease
      name: 'ingress-nginx'
