apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - ingress-nginx.yaml
  - metrics-server.yaml
  - sealed-secrets.yaml
  - secret-weave-gitops-cluster-user-auth.yaml
  - weave-gitops-dashboard.yaml
