---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 30m
  chart:
    spec:
      chart: metrics-server
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: metrics-server
      interval: 12h
  values:
    installCRDs: true
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  summary: "Cluster: microk8s, App: metrics-server"
  providerRef:
    name: slack
    namespace: flux-system
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'metrics-server'
    - kind: HelmRelease
      name: 'metrics-server'

