---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1h
  releaseName: kube-prometheus-stack
  targetNamespace: observability
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      enabled: false
      forceDeployDashboards: true
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: public
        annotations:
          cert-manager.io/cluster-issuer: selfsigned-ca
        hosts:
          - alertmanager.homelab.dimitrikoshkin.com
        tls:
          - secretName: alertmanager.homelab.dimitrikoshkin.com-tls
            hosts:
              - alertmanager.homelab.dimitrikoshkin.com
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
        alertmanagerConfiguration:
          name: slack-alertmanager-config
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    prometheus-node-exporter:
      prometheus:
        monitor:
          relabelings:
            - sourceLabels: [__meta_kubernetes_pod_node_name]
              targetLabel: node
    prometheus:
      ingress:
        enabled: true
        ingressClassName: public
        annotations:
          cert-manager.io/cluster-issuer: selfsigned-ca
        hosts:
          - prometheus.homelab.dimitrikoshkin.com
        tls:
          - secretName: prometheus.homelab.dimitrikoshkin.com-tls
            hosts:
              - prometheus.homelab.dimitrikoshkin.com
      prometheusSpec:
        retention: "15d"
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 40Gi
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  summary: "Cluster: ${CLUSTER_NAME}, App: kube-prometheus-stack"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: infra-kube-prometheus-stack
      namespace: flux-system
    - kind: HelmRelease
      name: kube-prometheus-stack
      namespace: flux-system
