---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-local-path-provisioner
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/csi/local-path-provisioner
  prune: false
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-sealed-secrets-controller
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/sealed-secrets-controller
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-metallb
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/service-loadbalancer/metallb
  prune: false
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-metallb-config
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-metallb
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/service-loadbalancer/metallb-config
  prune: false
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-ingress-controller
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-metallb-config
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/ingress-controller
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-cert-manager
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/cert-manager/controller
  prune: false
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-cert-issuers
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-cert-manager
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/cert-manager/cert-issuers
  prune: false
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-dashboard
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-sealed-secrets-controller
  - name: infra-ingress-controller
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/observability/flux-dashboard
  prune: false
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-sealed-secrets-controller
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/green/secrets
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-cloudflared
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-secrets
  - name: infra-metallb-config
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/cloudflared
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-uptime-kuma
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-ingress-controller
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/observability/uptime-kuma
  prune: false
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-observability-sources
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/observability/sources
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-observability-sources
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/observability/kube-prometheus-stack
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-prometheus-adapter
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-observability-sources
  - name: infra-kube-prometheus-stack
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/observability/prometheus-adapter
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-loki
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-observability-sources
  - name: infra-kube-prometheus-stack
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/observability/loki
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-alloy
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-observability-sources
  - name: infra-kube-prometheus-stack
  - name: infra-loki
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/observability/alloy
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-grafana
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-observability-sources
  - name: infra-kube-prometheus-stack
  - name: infra-loki
  - name: infra-ingress-controller
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/observability/grafana
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
