---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-sealed-secrets-controller
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/sealed-secrets-controller
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-cert-manager
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/cert-manager
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-cert-issuers
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-cert-manager
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/cert-issuers
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-dashboard
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-sealed-secrets-controller
  - name: infra-ingress-controller
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/flux-dashboard
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-sealed-secrets-controller
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/green/secrets
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: "green"

