---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 1h
  url: https://dirsigler.github.io/uptime-kuma-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 30m
  chart:
    spec:
      chart: uptime-kuma
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
      interval: 1h
  releaseName: uptime-kuma
  targetNamespace: uptime-kuma
  driftDetection:
    mode: enabled
  values:
    persistence:
      enabled: true
      size: 4Gi

    ingress:
      enabled: true
      className: public
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      hosts:
        - host: monitor-${CLUSTER_NAME}-apps.dimitrikoshkin.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: monitor-${CLUSTER_NAME}-apps.dimitrikoshkin.com-tls
          hosts:
            - monitor-${CLUSTER_NAME}-apps.dimitrikoshkin.com
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  summary: "Cluster: ${CLUSTER_NAME}, App: uptime-kuma"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: infra-uptime-kuma
      namespace: uptime-kuma
    - kind: HelmRelease
      name: uptime-kuma
      namespace: uptime-kuma