apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg-operator
  namespace: postgresql
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: postgresql
      interval: 1h
  values:
    # Operator configuration
    config:
      ENABLE_MONITORING: "false"
      # Watch only this namespace (more secure)
      WATCH_NAMESPACE: "postgresql"
