apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBL21no7naa/dJFMAwtP8hpcrLdH2+rez8RBJPNNQplyWU81zL3AEJbEOJa5eZzVJgIMRHFfErkBAUvZuzStqBSGeuUo3ITrsmeXvSbNXMuUhoPQqoLs8h7K0RReKd32SgU1mafz/nAQrXHGraZxy4Bvbu4QLwCWDEBRor87/Q9bN2048lH4MbGgRNEa+HujECOAfJdmyBupbLRZK14DHMw+ePs/KSa/W90acnn59Qvx0/Wd09H2tXey+jU3cponq4W6uDBDZpq1GfYp70VucUlVZmz9XtX42xxt8H9fHa2nRtLisFNMFD8jrngjyO07lSRBHrLAkPHlQfQFlCDdLHWS148ELAH9+dwEkWtFouHj64bGgZBtXzM/6ePqPsDxHaKn8EI0/QglHXckYeX0YtNFny1oJxkLz+XKvFfbVI30INt4ZcQV3LQUPqnU31SCU5uymWk3JqUclZggv6bldcWEuAiCoNhX82dkDGY62CUWw9OAUvXwxW2654svL+pDxv+y3yH/cdBWfZ3BwYA0hGaD5VLm8EoI5C5YsQQNZOxLASN43MQJpX06yB4XwxpR+hldA5LgB6a2PYY5trP3KZTb5uKJEUFqkOS0dfG3mEnDpX6Fxr6y4zMp0TxWCIzcx7QPW4NiEiYOHiYmcMjrhfKFDdAHwDdmNHUDUaaw6dEI3rRSw4CbDOozNPAqfeSQYjhEjYHYue0LQi/lKdX5Cduhgs3zhBW92U5sOc5OJlwL/g1yVTY84yZ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
