apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: teslamate
spec:
  encryptedData:
    api-token: AgAoCrk6V7fPlaIETu1v5f9waUYOEBw6pmilO1Sj7KJKSKEvPzmFXr8wMiG8sAavJzZY7AdfkU9NOETeZ6qtRAiANMRXvG6IPio6jmlDbLWTa1fIVrdRlb4NaLzvYpf2GWpaH4u3ho86aT73KjBn3m3QLX1uwZ7OYQLN0r+N+qatJikxadRiYp4jXRpIqE7Nz1RXzTt6CBzf8A78Q4NjMIvHIWlAWs6kg89xUjIuWxrdtW0aRVIwaLaIzGObodi8F3HxU1/wPTMTTgkOFvbFZmPR+eu3QsIpegu6jgyb3Oy5oyqDojYwvBhHoUXNK9vxtzK0RzWQrMPihI+TvjAU9h8HvzBsqv4aBzbrIk99zjh8YC9vAVpLTMI7n0FNaLSf6uThHj6j02yaBVpmaTL7q6Wp99MwcSW+ZzVxkQabh92SHa5/z92+lL2U2PD/owdOERqDes7JLDDpQsKc1oSnJcqvOYZJPD4fzQOBSINddzuWOon4vcppiy9M+9rG9RlPAxfQHp+6Auk1oJhazX0or69iGDn81DQciF/Jy0ABNvmjTspKREd8HaJcZNFJhZzeRDy/BgifRN7qhnxP7wtHn+LK6Dh32p1FmDcymaV+etM+G6IrCaLKGHmoOokVxIt6SkSqySYukRXiVthjgA2wXNJxrbPcHvOXDJOYgNktBLBhpwmyFI466/UiqeZbDnk9nDFt6+7hClOdsY2AcLatTrtlFLV84Xwm1nWh0ANvmVuoTjVW48HMpSe2qtlsCDC+/KE=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: teslamate
