apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-vip-cloud-controller.yaml
  - ingress-nginx.yaml
  - metrics-server.yaml
  - secret-weave-gitops-cluster-user-auth.yaml
  - weave-gitops-dashboard.yaml
  - secret-prometheus-stack-grafana.yaml
  - prometheus-stack.yaml
