---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: prometheus
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: prometheus
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: prometheus
      interval: 1h
  values:
    grafana:
      admin:
        existingSecret: prometheus-stack-grafana
      ingress:
        enabled: true
        ingressClassName: public
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-cloudflare
        hosts:
        - grafana-${CLUSTER_NAME}.dimitrikoshkin.com
        tls:
        - secretName: grafana-${CLUSTER_NAME}.dimitrikoshkin.com-tls
          hosts:
          - grafana-${CLUSTER_NAME}.dimitrikoshkin.com
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: prometheus-stack
  namespace: flux-system
spec:
  summary: "Cluster: ${CLUSTER_NAME}, App: prometheus-stack"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'prometheus-stack'
      namespace: prometheus
    - kind: HelmRelease
      name: 'prometheus-stack'
      namespace: prometheus
