---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: sealed-secrets
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      interval: 1h
  releaseName: sealed-secrets-controller
  targetNamespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  summary: "Cluster: ${CLUSTER_NAME}, App: sealed-secrets"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'sealed-secrets'
      namespace: flux-system
    - kind: HelmRelease
      name: 'sealed-secrets'
      namespace: flux-system
