apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgByB/hP3Pzp7aaWDMagHG80ejm/cbGhltvIBROp5LTVS8Sdxfr3qD8LmqEwB8uGDtGa+VSv+KPSx8BwIgANR9ETEUqVYsaX8DGIF9fLtIidiFrNlsu0NjP+eXacfi7fXjt4T0ZM9K4GjovEPa9SKFDpMPaFyZhrl920Jro9PDRHd5SvNBlXKj2kL5k3THz+DC26bQmRS8qNH6Jx8e1qY02bcdyNxKvh4d31+HGoDp91npUHnzRzNNIg+o3Ju01+1xpmqWz7H29NE5/NKti8JS9uFQyANkek+GlEGD1tFhYO8bOvkhiIvja7lnJJm/tURhxE/DcVTtAdvE4NnFrEaddu54UfTFiXbPXDGB2s+WMRVGt2MK4RzG/x9xDHgoDblpoNwCvg6NhZdA0rB36SxInsDwkruO4J8isIKV+fWMxUD5bkIYVupC6swjRqWWVGSnQTcsNNDHblGSW/fV+1Dc1RSnwyqXjYq4fkUXBmvLsTGy1NfL+LyJkhvsrt6iaZlqQRbJpvWPohFuEBg7J/HAUaPGmeCjsbITEp5g8sqIm8tjAp+5TL6iO8Wc2RYCJcRQL5cfkUchx42ASzNN/DBcPC6R/b6IuN2dkddpo4UkxUmHdPIa0bMMz1ZyVjeHJRnA3tuFL9pY26JRbupa34AJKRjl+QQBQtgEfX9rkqb1t7qyKV34muJIdgXrfNjt4iJH/AHwr/kFMdQmoZbgUqc01ECPocVSHPZKZjfU1xSfxLSrd/2IqTeUID17+Tw66YE116BerKdHLeqXt5EAE=
    username: AgA88vXOPgh8yQi8OUw1BPFaVjSgHC6Iv0QY+4S3BsQOKIv5Ena1JMXdqXdkXmsMaMfICyqbBS7LdZJYGifnD/ciHxCVdqm106I9Qv/2Jq8JKZnkbOh/e2DVGTlygFdkQSi9kCBhRmHXIMuGGCxKP0Jt5P1ekaASPf3IfRiPBcDss6yh752HtHU5JcwBzpw4CrEUgZuCs3S/ID9Sp2kzYEkYLj8aI4aWVjWQvj6lI427qcpExynXUPnFkfix9unuEaLwL3zJDWxn7EasPRHhMe/TJgH9i9RumkbLdS3AHRcTXhoYOhHKSnELKutP9folzHU4+bqWZNhnbrn8B5DHkFhhbk3m/Zo7DKCO1Ps4UxaYK0H1Mf1I/XCqd3X4kXCpTSeKzBozVAIQdDOdo9sQu+7aqpQbCyMxYUYmA2a+ab4UETkt1GJoT3EobZPSIAQRNSCPE3epxEknaP5Zoq+TOXzkrklEBT0EjvzmJnoGS2qo4aXi5mkeZYQ2CbYs+WIe2EDA7jI+jco4p344/htDDIZN3rQf9SwP1cQ3pLdJKVtx9fLt5DCRQRv49HZ9b/sfiA9ybfz1UEo9DjN81oHuEb/danPKVmHqPBANhRwk1LfdzJQehAhadQ39uuBtpIRZbtdkUnJ4EB++pjl49D5OJ93ZcIuR/YntWADc1XiDj2XuDJ3tBvCvZEaWyxFgRZwEiBaeew3G7g==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system

