apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: teslamate
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: teslamate
      interval: 1h
  values:
    admin:
      existingSecret: grafana-admin-auth
    # override the image with the Teslama Grafana image that has the charts baked in
    image:
      repository: teslamate/grafana
      tag: latest
    env:
      # serve Grafana from path /grafana
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      # these values are already set in the default template
      # override with the values that the Teslamate Grafana image expects
      GF_PATHS_CONFIG: "/etc/grafana/grafana.ini"
      GF_PATHS_DATA: "/var/lib/grafana"
      GF_PATHS_LOGS: "/var/log/grafana"
      GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
    envFromSecret: postgresql-db-auth
    ingress:
      enabled: true
      ingressClassName: public
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      path: /grafana
      hosts:
      - teslamate.dimitrikoshkin.com
      tls:
      - secretName: teslamate.dimitrikoshkin.com-tls
        hosts:
          - teslamate.dimitrikoshkin.com
