---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: grafana
  namespace: flux-system
spec:
  summary: "Cluster: ${CLUSTER_NAME}, App: grafana"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: grafana
      namespace: teslamate
    - kind: HelmRelease
      name: grafana
      namespace: teslamate
