apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: teslamate
  namespace: teslamate
spec:
  interval: 1m
  url: https://github.com/dkoshkin/teslamate-helm-chart
  ref:
    branch: main
