apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: kube-system
  annotations:
    cloudprovider.harvesterhci.io/ipam: pool
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: https-ingress
    port: 443
    protocol: TCP
    targetPort: https
  - name: http-ingress
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: rke2-ingress-nginx
    app.kubernetes.io/name: rke2-ingress-nginx
  type: LoadBalancer
